#!/usr/bin/env python2
import pygame
import sys
import os
import re
import random

def list_directory(path):
    for root, dirs, files in os.walk(path):
        for filename in files:
            yield os.path.join(root, filename)

if len(sys.argv) != 2:
    sys.stderr.write("Must specify exactly one path\n")
    sys.exit(2)
elif not os.path.isdir(sys.argv[1]):
    sys.stderr.write("Path must be a directory\n")
    sys.exit(2)

edges = {}
edgeRE = re.compile('.*/([^-]+)-([^-]+)\.(?:ogg|mp3)')
for filename in list_directory(sys.argv[1]):
    m = edgeRE.match(filename)
    if m:
        from_node = m.group(1)
        to_node = m.group(2)
        edges.setdefault(from_node, []).append((to_node, filename))

if 'start' in edges:
    node = 'start'
else:
    node = random.choice(edges.keys())

pygame.init()

END_MUSIC_EVENT = pygame.USEREVENT + 0    # ID for music Event
pygame.mixer.music.set_endevent(END_MUSIC_EVENT)

node, filename = random.choice(edges[node])
pygame.mixer.music.load(filename)
pygame.mixer.music.play()

pygame.event.post(pygame.event.Event(END_MUSIC_EVENT))
while True:
    event = pygame.event.poll()
    if event.type == END_MUSIC_EVENT:
        if filename:
            print filename
        else:
            break
        node, filename = random.choice(edges[node])
        if node:
            pygame.mixer.music.queue(filename)
    pygame.time.delay(100)

pygame.quit()
